<?= $this->renderTabs($this->tabs); ?>

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    <?= pm_Locale::lmsg("agent.view.title"); ?>
                </h3>
            </div>
        </div>
        <div class="content">
            <div>
                <?= pm_Locale::lmsg("agent.view.description"); ?>
                <br>
                <br>

                <div class="box-area">

                    <div class="form-row">
                        <div class="field-name">
                            <span><?= pm_Locale::lmsg("agent.view.installed.title"); ?>: </span>
                        </div>
                        <div class="field-value">
                            <span><?= pm_Locale::lmsg("msg.installed"); ?></span>
                        </div>
                    </div>
                        
                    <div class="form-row">
                        <div class="field-name">
                            <span><?= pm_Locale::lmsg("agent.view.version.title"); ?>: </span>
                        </div>
                        <div class="field-value">
                            <span><?= $this->agent_version; ?></span>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="field-name">
                            <span><?= pm_Locale::lmsg("agent.view.os.title"); ?>: </span>
                        </div>
                        <div class="field-value">
                            <span><?= $this->agent_os; ?></span>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="field-name">
                            <span><?= pm_Locale::lmsg("agent.view.arch.title"); ?>: </span>
                        </div>
                        <div class="field-value">
                            <span><?= $this->agent_arch; ?></span>
                        </div>
                    </div>

                </div>
            </div>

            <div class="btns-box">
                <?php if ($this->agent_outdated === "true"): ?>

                    <form method="post" action="<?= $this->h->url('update-agent', 'agent'); ?>">
                        <div class="box-area">
                            <div class="form-row">
                                <div class="field-name">
                                    <span class="required">*</span>
                                    <span> <?= pm_Locale::lmsg("msg.required"); ?></span>
                                </div>
                                <div class="field-value">
                                    <span class="btn action">
                                    
                                        <button type="submit" name="submit" value="updateAgent">
                                            <?= sprintf(pm_Locale::lmsg("agent.controller.update"), $this->update_version) ?>
                                        </button> 
                                    
                                    </span>
                                </div>
                            </div>
                        </div>
                    </form>
                <?php endif; ?>
            </div>
            
        </div>
    </div>
</div>

<!-- ========================================= [ JS ] ===================================================================== -->

<script>

    var setLoading = function (toggle) {
        
        // hide button
        toggle.style.display = "None";

        // disable parent
        var parent = toggle.parentNode;
        parent.classList.toggle("disabled");

        // rotating loading spinner
        var spinner = document.createElement("span");
        spinner.classList.toggle("wait");
        spinner.appendChild(document.createTextNode("Please wait"));

        parent.appendChild(spinner);
    } 

    var eventHandler = function (event) {

        // get the clicked element
        var toggle = event.target;

        if (toggle.nodeName.toLowerCase() === "button") {
            
            // for all submit buttons
            if (toggle.type === "submit") {

                // init loading
                setLoading(toggle);
            }
        }
    };

    document.addEventListener("click", eventHandler);

</script>