<?= $this->renderTabs($this->tabs); ?>

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Update Agent
                </h3>
            </div>
        </div>
        <div class="content">
            <div>
                <?= pm_Locale::lmsg("updateAgent") ?>
                <br>
                <br>

                <div class="box-area">

                    <div class="form-row">
                        <div class="field-name">
                            <span>Current agent status: </span>
                        </div>
                        <div class="field-value">
                            <span><?= pm_Locale::lmsg("agentInstalled"); ?></span>
                        </div>
                    </div>
                        
                    <div class="form-row">
                        <div class="field-name">
                            <span>Current agent version: </span>
                        </div>
                        <div class="field-value">
                            <span><?= $this->agent_version; ?></span>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="field-name">
                            <span>Current agent operating system: </span>
                        </div>
                        <div class="field-value">
                            <span><?= $this->agent_os; ?></span>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="field-name">
                            <span>Current agent architecture: </span>
                        </div>
                        <div class="field-value">
                            <span><?= $this->agent_arch; ?></span>
                        </div>
                    </div>

                </div>
            </div>

            <?= $this->form; ?>
            
        </div>
    </div>
</div>