<?= $this->response; ?>
<?= $this->renderTabs($this->tabs); ?> 

<!-- ========================================= [ UNREGISTERED DOMAINS ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    <?= $this->lmsg("settings.view.unreg.title"); ?>
                </h3>
            </div>
        </div>
        <div class="content">
            <?= $this->lmsg("settings.view.unreg.description"); ?>
            <br>
            <br>

            <form method="post" id="register" action="<?= $this->h->url('register', 'settings'); ?>">
                <div class="form-row">
                    
                    <div class="field-name" style="width: 250px;">
                        <select name="bundle" style="width: 250px;">
                            <?php foreach ($this->registered_domains as $bundle_id => $bundle_element): ?>

                                <?php $value = "{$bundle_id}__{$bundle_element['bundle']['name']}"; ?>
                                <option value="<?= $value ?>"><?= $bundle_element['bundle']['display']; ?></option>

                            <?php endforeach; ?>
                        </select>
                    </div>
                    
                    <div class="field-value">
                        <?php if (count($this->nonregistered_domains) > 0): ?>
                            <span id="btn-send" class="btn action" style="margin-left: 20px;">
                            
                                <button type="submit" name="submit" value="registerSelected">
                                    <?= $this->lmsg("settings.view.unreg.register"); ?>
                                </button>
                            
                            </span>
                        <?php endif; ?>
                    </div>
                    <br>
                    
                    <div class="list">
                        <?php if (count($this->nonregistered_domains) == 0): ?>
                        
                            <span class="hint">
                                <?= $this->lmsg("settings.view.unreg.no_domains"); ?>
                            </span>
                        
                        <?php else: ?>
                            <table width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>
                                            <input name="act0" id="act0" type="checkbox" setter> <?= $this->lmsg("settings.view.unreg.domain"); ?>
                                        </th>
                                        <th>
                                            <a><?= $this->lmsg("msg.directory"); ?></a>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->nonregistered_domains as $domain => $directory): ?>
                                    <tr class=" odd" data-row-id="">
                                        <td class="">
                                            <input name="active0[]" value="<?= $domain; ?>" type="checkbox"> <?= $domain; ?>
                                        </td>
                                        <td class="">
                                            <?= $directory; ?>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php endif; ?>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>
<br>

<!-- ========================================= [ REGISTERED DOMAINS ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    <?= $this->lmsg("settings.view.reg.title"); ?>
                </h3>
            </div>
        </div>
        
        <div class="content">
            <?= $this->lmsg("settings.view.reg.description"); ?>
            <br>
            <br>

            <?php $i = 1; ?>
            <?php foreach ($this->registered_domains as $bundle_element): ?>

                <form method="post" action="<?= $this->h->url('unregister', 'settings'); ?>">
                    <input type="hidden" name="bundle" value="<?= $bundle_element["bundle"]["name"]; ?>"/>
                    <div class="form-row">
                        
                        <div class="field-name">
                            <h5><b><?= $bundle_element["bundle"]["name"]; ?></b></h5>
                        </div>
                        
                        <div class="field-value">
                            <?php if (count($bundle_element["domains"]) > 0): ?>
                                <span id="btn-send" class="btn action">
                                
                                    <button type="submit" name="submit" value="removeSelected<?= $i; ?>">
                                        <?= $this->lmsg("settings.view.reg.unregister"); ?>
                                    </button>
                                
                                </span>
                            <?php endif; ?>
                        </div>

                        <div class="list">
                            <?php if (count($bundle_element["domains"]) == 0): ?>
                            
                                <span class="hint">
                                    <?= $this->lmsg("settings.view.reg.no_domains"); ?>
                                </span>
                            
                            <?php else: ?>
                                <table>
                                    <thead>
                                        <tr>
                                            <th>
                                                <input name="act<?= $i; ?>" id="act<?= $i; ?>" type="checkbox" setter> <?= $this->lmsg("settings.view.reg.domain"); ?> 
                                            </th>
                                            <th>
                                                <a><?= $this->lmsg("msg.directory"); ?></a>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($bundle_element["domains"] as $domain): ?>
                                            <tr>
                                                <td>
                                                    <input name="active<?= $i; ?>[]" value="<?= $domain['name']; ?>" type="checkbox"> <?= $domain['name']; ?>
                                                </td>
                                                <td>
                                                    <?= $domain["directory"]; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            <?php endif; ?>
                        </div>

                    </div>
                </form>
                
                <?php if ($i == count($this->registered_domains)): ?>
                    <br>
                    <br>
                    <div class="btns-box" style="border-top: 3px solid #ddd;"></div>
                    <br>
                <?php else: ?>
                    <div class="btns-box"></div>
                    <br>
                <?php endif; ?>

            <?php $i = $i + 1; ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<!-- ========================================= [ AGENT CONFIGURATION ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    <?= $this->lmsg("settings.view.conf.title"); ?>
                </h3>
            </div>
        </div>
        <div class="content">
            <?= $this->lmsg("settings.view.conf.description"); ?>
            <br>
            <br>
            <div class="form-row">
                <div class="field-name">
                    <?= $this->lmsg("settings.view.conf.configuration"); ?>
                </div>
                <div class="field-value">
                    <textarea style="margin-right: 5px; height: 400px; width: 400px" readonly><?= $this->configuration; ?></textarea>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- ========================================= [ SCHEDULE SETTINGS ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    <?= $this->lmsg("settings.view.schedule.title"); ?>
                </h3>
            </div>
        </div>
        <div class="content">
            <?= $this->lmsg("settings.view.schedule.description"); ?>
            <br>
            <br>
            
            <form method="post" id="schedule" action="<?= $this->h->url('schedule', 'settings'); ?>">

                <!-- scheduled -->
                <?php $agent_scheduled = pm_Settings::get("agent_scheduled"); ?>
                <input name="status" value="true" type="checkbox" style="margin-right: 5px; margin-bottom: 10px;"
                    <?php if ($agent_scheduled === "true"): ?> checked="checked" <?php endif; ?> /> <?= $this->lmsg("settings.view.schedule.status"); ?>    
                <br>
                
                <!-- yara -->
                <?php $agent_arch = json_decode(pm_Settings::get("agent"), true)["arch"]; ?>
                <?php $agent_yara = pm_Settings::get("agent_yara"); ?>

                <input name="yara" value="true" type="checkbox" style="margin-right: 5px; margin-bottom: 10px;"
                    <?php if ($agent_arch === "32bit"): ?> disabled="disabled" <?php endif ?>
                    <?php if ($agent_yara === "true"): ?> checked="checked" <?php endif ?> /> 
                    <?= $this->lmsg("settings.view.schedule.yara"); ?> <?php if ($agent_arch === "32bit"): ?><?= $this->lmsg("settings.view.schedule.yara_not_supported"); ?><?php endif ?>

                <!-- interval -->
                <div class="form-row">
                    <div class="field-name">
                        <?= $this->lmsg("settings.view.schedule.interval"); ?>
                    </div>
                    <div class="field-value">
                        <select name="interval"> 
                            <option value="0" <?php if (pm_Settings::get("agent_schedule_interval") == "0"): ?> selected <?php endif; ?>>
                                <?= $this->lmsg("settings.view.schedule.interval.once"); ?>
                            </option>
                            <option value="12" <?php if (pm_Settings::get("agent_schedule_interval") == "12"): ?> selected <?php endif; ?>>
                                <?= $this->lmsg("settings.view.schedule.interval.twice"); ?>
                            </option>
                            <option value="8" <?php if (pm_Settings::get("agent_schedule_interval") == "8"): ?> selected <?php endif; ?>>
                                <?= $this->lmsg("settings.view.schedule.interval.three_times"); ?>
                            </option>
                            <option value="6" <?php if (pm_Settings::get("agent_schedule_interval") == "6"): ?> selected <?php endif; ?>>
                                <?= $this->lmsg("settings.view.schedule.interval.four_times"); ?>
                            </option>
                        </select>
                    </div>
                </div>
                <div class="btns-box">
                    <div class="box-area">
                        <div class="form-row">
                            <div class="field-name">
                                <span id="btn-send" class="btn action">
                                    <button type="submit" name="submit" value="schedule">
                                        <?= $this->lmsg("settings.view.schedule.update"); ?>    
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- ========================================= [ JS ] ===================================================================== -->

<script>

    var setLoading = function (toggle) {
        
        // hide button
        toggle.style.display = "None";

        // disable parent
        var parent = toggle.parentNode;
        parent.classList.toggle("disabled");

        // rotating loading spinner
        var spinner = document.createElement("span");
        spinner.classList.toggle("wait");
        spinner.appendChild(document.createTextNode("Please wait"));

        parent.appendChild(spinner);
    } 

    var eventHandler = function (event) {

        // get the clicked element
        var toggle = event.target;

        if (toggle.nodeName.toLowerCase() === "button") {
            
            // for all submit buttons
            if (toggle.type === "submit") {

                // init loading
                setLoading(toggle);
            }
        }

        if (toggle.nodeName.toLowerCase() === "input") {

            // toggle all checkboxes
            if (toggle.type === "checkbox" && toggle.hasAttribute ("setter")) {

                var index = toggle.name.slice(-1);
                document.getElementsByName("active" + index + "[]").forEach(function(element) {
                    element.checked = toggle.checked;
                });
            }
        }
    };

    document.addEventListener("click", eventHandler);
</script>