<?= $this->renderTabs($this->tabs); ?> 
<?= implode($this->responses); ?>

<link href="https://cdn.materialdesignicons.com/1.9.32/css/materialdesignicons.min.css" media="all" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css" rel="stylesheet">

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Issues
                </h3>
            </div>
        </div>
        <div class="content">
            <div class="form-row">
                <div class="field-name">
                    Bulk actions
                </div>
                <div class="field-value">
                    <div style="display: inline-block; margin-right: 10px;">
                        <div id="issue-dropdown" class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false" style="color: black;">
                                <span>Select action</span>
                                <i class="mdi mdi-menu-down"></i>
                            </a>
                            <ul class="dropdown-menu" style="background-color: #fafafa; box-shadow: 0 1px 4px 0px rgb(0, 0, 0, 0.3);">
                                <li><!-- <form method="post" action="/domain/result-id"> -->
                                    <a>
                                        <i class="mdi mdi-bug"></i>
                                        <span>Move to Quarantine</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div style="display: inline-block;">
                        <a id="issue-link">Select / Deselect all issues</a></div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="field-name">
                    Automatically move domains to quarantine
                </div>
                <div class="field-value">
                    <span style="margin-right: 2px;">
                        <span>None</span>
                        <input type="radio" name="quarantine-state" checked="checked"/>
                        <span style="color: #303030;">|</span>
                    </span>
                    <span style="margin-right: 2px;">
                        <i class="mdi mdi-checkbox-blank-circle" style="color: #fdd835"></i>
                        <span>Yellow</span>
                        <input type="radio" name="quarantine-state"/>
                        <span style="color: #303030;">|</span>
                    </span>
                    <span style="margin-right: 2px;">
                        <i class="mdi mdi-checkbox-blank-circle" style="color: #f44336"></i>
                        <span>Red</span>
                        <input type="radio" name="quarantine-state"/>
                    </span>
                </div>
            </div>
            
            <div class="btns-box"></div>

            <?php if (count($this->issues) == 0): ?>
                <h5>Congratulations! No issues found.</h5>
            <?php endif; ?>

            <?php foreach ($this->issues as $name => $domain): ?>
                <div class="form-row">

                    <div class="field-name" style="width: 100%">
                        <div style="display: inline-block;">
                            <h4><b><?= $name ?></b></h4>
                        </div>
                        <div style="display: inline-block; margin-left: 5px;">
                            <a id="issue-link-<?= $name; ?>">Select / Deselect all issues</a>
                        </div>
                    </div>

                    <div class="field-value" style="margin-bottom: 15px;"></div>

                    <?php foreach ($domain["results"] as $result): ?>
                        <div class="panel panel-collapsible p-promo panel-collapsed">
                            <div class="panel-wrap">

                                <div class="panel-heading">
                                    <div class="panel-heading-wrap">
                                        <span class="panel-control">

                                            <div style="margin-left: -140px; color: #303030; margin-top: 2px;display: inline-block;">
                                                    <?= date("m/d/o h:i A", $result["lastDate"] / 1000); ?>                                           
                                            </div>
                                            <div style="margin-left: -236px; display: inline-block;">
                                                <form method="post">
                                                    <input name="action" value="falsePositive" type="hidden"/>
                                                    <input name="domain" value="<?= $name; ?>" type="hidden"/>
                                                    <input name="resultId" value="<?= $result['id']; ?>" type="hidden"/>
                                                    <input name="file" value="<?= $result['resource'];?>" type="hidden">
                                                    <a onclick="sendForm(this);">
                                                        <i class="mdi mdi-flag"></i>
                                                        <span>False positive</span>
                                                    </a>
                                                </form>
                                            </div>
                                            <div style="margin-left: -246px; margin-top: 2px;display: inline-block;">
                                                <form method="post">
                                                    <input name="action" value="moveToQuarantine" type="hidden">
                                                    <input name="domain" value="<?= $name; ?>" type="hidden">
                                                    <input name="file" value="<?= $result['resource'];?>" type="hidden">
                                                    <a onclick="sendForm(this);">
                                                        <i class="mdi mdi-bug"></i>
                                                        <span>Move to Quarantine</span>
                                                    </a>
                                                </form>
                                            </div>

                                        </span>

                                        <div class="panel-heading-name">
                                            
                                            <?php
                                                $circle0 = "#bbb";
                                                $circle1 = "#fdd835";
                                                $circle2 = "#f44336";

                                                $bubbleColors = array(
                                                    $circle0, $circle0
                                                );

                                                if ($result["severity"] == 1) {
                                                    $bubbleColors[0] = $circle1;
                                                }

                                                if ($result["severity"] > 1) {
                                                    $bubbleColors[1] = $circle2;
                                                }
                                            ?> 

                                            <span style="margin-right: 5px">
                                                <input type="checkbox" id="issue-<?= $name;?>"/>
                                                <i class="mdi mdi-checkbox-blank-circle" style="color: <?= $bubbleColors[0]; ?>"></i>
                                                <i class="mdi mdi-checkbox-blank-circle" style="color: <?= $bubbleColors[1]; ?>"></i>
                                            </span>

                                            <span style="font-size: 13px">
                                                <?= $result["resource"]; ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel-content">
                                    <div class="panel-content-wrap">
                                        <?php foreach ($result as $key => $value): 
                                                $title = "";
                                                $text = $value;

                                                if ($key == "createDate") {
                                                    $title = "Known since";
                                                    $text = date("m/d/o h:i A", $value / 1000);
                                                }

                                                if ($key == "threatname") {
                                                    $title = "Name";
                                                }

                                                if ($key == "resource") {
                                                    $title = "Path";
                                                }

                                                if ($key == "md5") {
                                                    $title = strtoupper($key);
                                                }

                                                if ($key == "owner" || $key == "group" || $key == "permission") {
                                                    $title = ucfirst($key);
                                                }

                                                if ($title == "") {
                                                    continue;
                                                }
                                        ?>
                                        
                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>
                                                        <?= $title; ?>
                                                    </span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= $text; ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <?php endforeach; ?>

                                        <div class="source-code">
                                            <a>View source code <i id="source-code-icon" class="mdi mdi-arrow-down-drop-circle"></i></a>
                                        </div>
                                        
                                        <div class="panel panel-collapsible panel-collapsed" style="margin: 0px; border: 0px">
                                            <div class="panel-wrap">
                                                <div class="panel-content">
                                                    <div class="panel-content-wrap">
                                                        <pre><code class="html">
                                                            <?= htmlentities(file_get_contents($result["resource"])); ?>
                                                        </code></pre>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    
                    </div>
                </div>
            <?php endforeach; ?> 

        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<script>

    function sendForm(element) {
        element.closest("form").submit();
    }

    // show issue dropdown
    document.querySelectorAll("[id='issue-dropdown']").forEach(function(menu) { 
        menu.querySelector(".dropdown-toggle").addEventListener("click", function(triggered) {
            triggered.target.closest("#issue-dropdown").classList.toggle("open");
        });
    });

    // checking / unchecking domains
    document.querySelectorAll("[id^='issue-link']").forEach(function(link) { 
        link.addEventListener("click", function(triggered) { 
            var parts = triggered.target.id.split("-"); 
            if (parts.length < 3) {
                var checked = document.querySelector("input[id^='issue-']").checked;
                checked = !checked;

                document.querySelectorAll("input[id^='issue-']").forEach(function (issue) { issue.checked = checked; });
                return;
            }

            var domain = parts[parts.length - 1];
            var checked = document.querySelector("[id='issue-" + domain + "']").checked;
            checked = !checked;

            document.querySelectorAll("[id='issue-" + domain + "']").forEach(function(issue) { issue.checked = checked; });
        }); 
    });

    // expand issue panel
    Array.from(document.getElementsByClassName("panel-heading")).forEach(function(panel) { 
        panel.addEventListener("click", function(triggered) {
            if (triggered.target.parentElement.tagName == "A") {
                return;
            }

            triggered.target.closest(".panel").classList.toggle("panel-collapsed");
            triggered.target.closest(".panel").classList.toggle("panel-expanded");
        });
    });

    // source-code expanding / collapsing
    Array.from(document.getElementsByClassName("source-code")).forEach(function(item) { 
        item.addEventListener("click", function(triggered) {
            var panel = triggered.target.parentElement.nextElementSibling;
            var icon = triggered.target.querySelector("#source-code-icon");

            panel.classList.toggle("panel-collapsed");
            panel.classList.toggle("panel-expanded");

            panel.style.cssText = collapsed ? "border: 0px; margin: 0px;" : ""; 

            icon.classList.toggle("mdi-arrow-down-drop-circle");
            icon.classList.toggle("mdi-arrow-up-drop-circle");
        });
    });

</script>