<?= $this->renderTabs($this->tabs); ?> 
<?= implode($this->responses); ?>

<!-- ========================================= [ UNREGISTERED DOMAINS ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Unregistered Domains
                </h3>
            </div>
        </div>
        <div class="content">
            Below you can find your domains inside of plesk which has not been registered with Nimbusec. In order to register a domain, select the domain you want to register
            along with the bundle<br>
            and click on the button "Register the selected domains" to complete the registration.
            <br>
            <br>

            <form method="post" id="register">
                <div class="form-row">
                    
                    <div class="field-name" style="width: 250px;">
                        <select name="bundle" style="width: 250px;">
                            <?php foreach ($this->fetched as $id => $element): ?>

                                <?php $value = "{$id}__{$element['bundle']['name']}"; ?>
                                <option value="<?= $value ?>"><?= $element['bundle']['display']; ?></option>

                            <?php endforeach; ?>
                        </select>
                    </div>
                    
                    <div class="field-value">
                        <?php if (count($this->domains) > 0): ?>
                            <span id="btn-send" class="btn action" style="margin-left: 20px;">
                                <button type="submit" name="submit" value="registerSelected">Register the selected domains</button>
                            </span>
                        <?php endif; ?>
                    </div>
                    <br>
                    
                    <div class="list">
                        <?php if (count($this->domains) == 0): ?>
                            <span class="hint">
                                No domains found.
                            </span>
                        <?php else: ?>
                            <table width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>
                                            <input name="act0" onclick="updateState(0)" id="act0" type="checkbox"> Register domain 
                                        </th>
                                        <th>
                                            <a>Directory</a>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->domains as $domain => $directory): ?>
                                    <tr class=" odd" data-row-id="">
                                        <td class="">
                                            <input name="active0[]" value="<?= $domain; ?>" type="checkbox"> <?= $domain; ?>
                                        </td>
                                        <td class="">
                                            <?= $directory; ?>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php endif; ?>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>
<br>

<!-- ========================================= [ REGISTERED DOMAINS ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Registered domains
                </h3>
            </div>
        </div>
        
        <div class="content">
            Below you can find your registered domains with their corresponding bundle. To unregister a bundle, select it on the checkbox and click on the button to complete the unregistration.
            <br>
            <br>

            <?php $i = 1; ?>
            <?php foreach ($this->fetched as $id => $element): ?>

                <form method="post">
                    <input type="hidden" name="bundle" value="<?= $element["bundle"]["name"]; ?>"/>
                    <div class="form-row">
                        
                        <div class="field-name">
                            <h5><b><?= $element["bundle"]["name"]; ?></b></h5>
                        </div>
                        
                        <div class="field-value">
                            <?php if (count($element["domains"]) > 0): ?>
                                <span id="btn-send" class="btn action">
                                    <button type="submit" name="submit" value="removeSelected<?= $i; ?>">Remove selected domains</button>
                                </span>
                            <?php endif; ?>
                        </div>

                        <div class="list">
                            <?php if (count($element["domains"]) == 0): ?>
                                <span class="hint">
                                    No registered domains found for this bundle.
                                </span>
                            <?php else: ?>
                                <table>
                                    <thead>
                                        <tr>
                                            <th>
                                                <input name="act<?= $i; ?>" id="act<?= $i; ?>" type="checkbox" onclick="updateState(<?= $i; ?>)"> Unregister domain 
                                            </th>
                                            <th>
                                                Directory
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($element["domains"] as $domain): ?>
                                            <tr>
                                                <td>
                                                    <input name="active<?= $i; ?>[]" value="<?= $domain['name']; ?>" type="checkbox"> <?= $domain['name']; ?>
                                                </td>
                                                <td>
                                                    <?= Modules_NimbusecAgentIntegration_PleskHelper::getDomainDir($domain["name"]); ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            <?php endif; ?>
                        </div>

                    </div>
                </form>
                
                <?php if ($i == count($this->fetched)): ?>
                    <br>
                    <br>
                    <div class="btns-box" style="border-top: 3px solid #ddd;"></div>
                    <br>
                <?php else: ?>
                    <div class="btns-box"></div>
                    <br>
                <?php endif; ?>

            <?php $i = $i + 1; ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<!-- ========================================= [ AGENT CONFIGURATION ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Agent Configuration
                </h3>
            </div>
        </div>
        <div class="content">
            <?= $this->configInfo; ?>
            <br><br>
            <div class="form-row">
                <div class="field-name">
                    Configuration
                </div>
                <div class="field-value">
                    <textarea style="margin-right: 5px; height: 400px; width: 400px" readonly><?= $this->configuration; ?></textarea>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- ========================================= [ RUN SETTINGS ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Run Settings
                </h3>
            </div>
        </div>
        <div class="content">
            <?= $this->runInfo; ?>
            <br>
            <br>
            
            <form method="post" id="schedule">

                <!-- scheduled -->
                <?php $agent_scheduled = pm_Settings::get("agent_scheduled"); ?>
                <input name="status" value="true" type="checkbox" style="margin-right: 5px; margin-bottom: 10px;"
                    <?php if ($agent_scheduled === "true"): ?> checked="checked" <?php endif; ?> /> <?= pm_Locale::lmsg("agentStatus"); ?>    
                <br>
                
                <!-- yara -->
                <?php $agent_arch = json_decode(pm_Settings::get("agent"), true)["arch"]; ?>
                <?php $agent_yara = pm_Settings::get("agent_yara"); ?>

                <input name="yara" value="true" type="checkbox" style="margin-right: 5px; margin-bottom: 10px;"
                    <?php if ($agent_arch === "32bit"): ?> disabled="disabled" <?php endif ?>
                    <?php if ($agent_yara === "true"): ?> checked="checked" <?php endif ?> /> 
                    <?= pm_Locale::lmsg("agentYara"); ?> <?php if ($agent_arch === "32bit"): ?><?= pm_Locale::lmsg("agentYaraNotSupported32Bit"); ?><?php endif ?>

                <!-- interval -->
                <div class="form-row">
                    <div class="field-name">
                        Agent Scan Interval
                    </div>
                    <div class="field-value">
                        <select name="interval"> 
                            <option value="0" <?php if (pm_Settings::get("schedule-interval") == "0"): ?> selected <?php endif; ?>>
                                <?= pm_Locale::lmsg("once"); ?>
                            </option>
                            <option value="12" <?php if (pm_Settings::get("schedule-interval") == "12"): ?> selected <?php endif; ?>>
                                <?= pm_Locale::lmsg("twice"); ?>
                            </option>
                            <option value="8" <?php if (pm_Settings::get("schedule-interval") == "8"): ?> selected <?php endif; ?>>
                                <?= pm_Locale::lmsg("threeTimes"); ?>
                            </option>
                            <option value="6" <?php if (pm_Settings::get("schedule-interval") == "6"): ?> selected <?php endif; ?>>
                                <?= pm_Locale::lmsg("fourTimes"); ?>
                            </option>
                        </select>
                    </div>
                </div>
                <div class="btns-box">
                    <div class="box-area">
                        <div class="form-row">
                            <div class="field-name">
                                <span id="btn-send" class="btn action">
                                    <button type="submit" name="submit" value="schedule">Save settings</button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- ========================================= [ JS ] ===================================================================== -->

<script>
    document.getElementsByName("submit").forEach((node) => { 
        node.addEventListener("click", function(obj) { 
            obj.target.style.display = "None";
            
            var parent = obj.target.parentNode;
            parent.classList.add("disabled");

            var wait = document.createElement("span");
            wait.classList.add("wait");
            wait.appendChild(document.createTextNode("Please wait"));

            parent.appendChild(wait);
        }); 
    });
    document.getElementById("configuration").readOnly = true;

    function updateState(id) {
        var elements = document.getElementsByName("active" + id + "[]");
        var target = document.getElementById("act" + id).checked;

        for (var i = 0; i < elements.length; i++) {
            elements[i].checked = target;
        }
    }
</script>