<?php 
foreach ($this->responses as $response) {
    echo $response;
}

echo $this->renderTabs($this->tabs); 
?>

<!-- ========================================= [ UNREGISTERED DOMAINS ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Unregistered Domains
                </h3>
            </div>
        </div>
        <div class="content">
            Here you can find your domains inside of plesk which has not been registered into nimbusec. In order to register a domain, select the domain you want to register
            along with the bundle<br>
            and click on the button "Register the selected domains" to complete the registration.
            <br>
            <br>
            <br>
            <form method="post" id="register">
                <div class="form-row">
                    <div class="field-name">
                        <select name="bundle">
                            <?php
                                foreach ($this->fetched as $id => $element) {
                                    echo "<option value='{$id}__{$element['bundle']['name']}'>{$element['bundle']['display']}</option>";
                                }
                            ?>
                        </select>
                    </div>
                    <div class="field-value">
                        <?php if (count($this->domains) > 0) { ?>
                            <span id="btn-send" class="btn action">
                                <button type="submit" name="submit" value="registerSelected">Register the selected domains</button>
                            </span>
                        <?php } ?>
                    </div>
                    <br>
                    <div class="list">
                        <?php if (count($this->domains) == 0) { ?>
                            <span class="hint">
                                No unregistered domains found.
                            </span>
                        <?php } else { ?>
                            <table id="pm-list-nimbusec-agent-integration-table" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>
                                            <input name="act0" onclick="updateState(0)" id="act0" type="checkbox"> Register domain 
                                        </th>
                                        <th>
                                            <a>Directory</a>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->domains as $domain => $directory) { ?>
                                    <tr class=" odd" data-row-id="">
                                        <td class="">
                                            <input name="active0[]" value="<?php echo $domain; ?>" type="checkbox"> <?php echo $domain; ?>
                                        </td>
                                        <td class="">
                                            <?php echo $directory; ?>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        <?php } ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br/>

<!-- ========================================= [ REGISTERED DOMAINS ] ===================================================================== -->

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Registered domains
                </h3>
            </div>
        </div>
        <div class="content">
            Below you can find your registered domains with their corresponding bundle. To unregister a bundle, select it on the checkbox and click on the button to complete the unregistration.
            <br/>
            <br/>
            <br/>
            <?php $i = 1; ?>
            <?php foreach ($this->fetched as $id => $element) { ?>
                <form method="post" id="unregister">
                    <input type="hidden" name="bundle" value="<?php echo $element["bundle"]["name"]; ?>"/>
                    <div class="form-row">
                        <div class="field-name">
                            <h5><b><?php echo $element["bundle"]["name"]; ?></b></h5>
                        </div>
                        <div class="field-value">
                            <?php if (count($element["domains"]) > 0) { ?>
                                <span id="btn-send" class="btn action">
                                    <button type="submit" name="submit" value="removeSelected<?php echo $i; ?>">Remove selected domains</button>
                                </span>
                            <?php } ?>
                        </div>
                        <div class="list">
                            <?php if (count($element["domains"]) == 0) { ?>
                                <span class="hint">
                                    No registered domains found for this bundle.
                                </span>
                            <?php } else { ?>
                                <table id="pm-list-nimbusec-agent-integration-table" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>
                                                <input name="act<?php echo $i; ?>" 
                                                    onclick="updateState(<?php echo $i; ?>)" 
                                                    id="act<?php echo $i; ?>" 
                                                    type="checkbox"> Unregister domain 
                                            </th>
                                            <th>
                                                Directory
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($element["domains"] as $domain) { ?>
                                        <tr class=" odd" data-row-id="">
                                            <td class="">
                                                <input name="active<?php echo $i; ?>[]" value="<?php echo $domain['name']; ?>" type="checkbox"> <?php echo $domain['name']; ?>
                                            </td>
                                            <td>
                                                <?php echo Helpers::getDomainDir($domain["name"]); ?>
                                            </td>
                                        </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            <?php } ?>
                        </div>
                    </div>
                </form>
                <div class="btns-box"></div>
                <br/>
            <?php $i = $i + 1; ?>
            <?php } ?>
        </div>
    </div>
</div>

<!-- ========================================= [ JS ] ===================================================================== -->

<script>
    document.getElementsByName("submit").forEach((node) => { 
        node.addEventListener("click", function(obj) { 
            obj.target.textContent = "";
            
            var parent = obj.target.parentNode;
            parent.classList.add("disabled");

            var wait = document.createElement("span");
            wait.classList.add("wait");
            wait.appendChild(document.createTextNode("Please wait"));

            parent.appendChild(wait);
        }); 
    });
</script>