<?php 
if ($this->submitted == true) {
	echo '<div class="msg-box msg-info"><div class="msg-content"><span class="title">Information</span>'.$this->infomsg.'</div></div>';
}
?>
<?php echo $this->renderTabs($this->tabs); ?>
<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Domains
                </h3>
            </div>
        </div>
        <div class="content">
            <form method="post">
                <div class="form-row">
                    <input type="hidden" name="submitted" value="submitted"/>
                    <div class="field-name">
                        <span>Select a nimbusec Bundle:</span>
                    </div>
                    <div class="field-value">
                        <select name="bundle">
                            <?php
                                foreach ($this->bundles as $id => $bundle) {
                                    echo "<option value='{$id}'>{$bundle}</option>";
                                }
                            ?>
                        </select>
                    </div>
                    <?php echo $this->renderList($this->list); ?>
                    <div class="btns-box">
                        <div class="box-area">
                            <div class="form-row">
                                <div class="field-name">
                                    Update the selected domains
                                </div>
                                <div class="field-value">
                                    <span id="btn-send" class="btn action">
                                        <button type="submit" name="submit" value="updateDomains">Update</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>