<?php echo $this->renderTabs($this->tabs); 

foreach ($this->responses as $response) {
    echo $response;
}
?>
<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Setup
                </h3>
            </div>
        </div>
        <div class="content">
            <?php echo $this->info; ?>
            <br>
            <br>
            
            <form method="post">

                <?php
                    $apikey = "Your Nimbusec API Key";
                    $apisecret = "Your Nimbusec API Secret";

                    if (!empty(pm_Settings::get('apikey'))) {
                        $apikey = pm_Settings::get('apikey');
                    }

                    if (!empty(pm_Settings::get('apisecret'))) {
                        $apisecret = pm_Settings::get('apisecret');
                    }
                ?>

                <!-- API key -->
                <div class="form-row">
                    <div class="field-name">
                        <span>API Key </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="apikey" value="<?php echo $apikey; ?>" <?php if (pm_Settings::get("setupTabs") == "0") { ?> readonly="true" <?php } ?>/>
                    </div>
                </div>

                <!-- API secret -->
                <div class="form-row">
                    <div class="field-name">
                        <span>API Secret </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="apisecret" value="<?php echo $apisecret; ?>" <?php if (pm_Settings::get("setupTabs") == "0") { ?> readonly="true" <?php } ?>/>
                    </div>
                </div>

                <!-- API server -->
                <div class="form-row">
                    <div class="field-name">
                        <span>API Server </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="apiserver" value="https://api.nimbusec.com" <?php if (pm_Settings::get("setupTabs") == "0") { ?> readonly="true" <?php } ?>/>
                    </div>
                </div>

                <div class="btns-box">
                    <?php if (pm_Settings::get("setupTabs") != "0") { ?>
                        <div class="box-area">
                            <div class="form-row">
                                <div class="field-name">
                                    <span class="required">*</span>
                                    <span> Required fields</span>
                                </div>
                                <div class="field-value">
                                    <span class="btn action">
                                        <button type="submit" name="submit" value="downloadAgent">Download Server Agent</button> 
                                    </span>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>

            </form>
        </div>
    </div>
</div>

<!-- ========================================= [ JS ] ===================================================================== -->

<script>
    document.getElementsByName("submit").forEach((node) => { 
        node.addEventListener("click", function(obj) { 
            obj.target.style.display = "None";
            
            var parent = obj.target.parentNode;
            parent.classList.add("disabled");

            var wait = document.createElement("span");
            wait.classList.add("wait");
            wait.appendChild(document.createTextNode("Please wait"));

            parent.appendChild(wait);
        }); 
    });
</script>