<?php echo $this->renderTabs($this->tabs); ?>
<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Update Agent
                </h3>
            </div>
        </div>
        <div class="content">
            <div>
                <?php echo $this->info; ?>
                <br><br>
                <div class="box-area">
                    <div class="form-row">
                        <div class="field-name">
                            <span>Current agent status: </span>
                        </div>
                        <div class="field-value">
                            <span><?php echo "{$this->agentStatus}"; ?></span>
                        </div>
                    </div>
                    <?php if ($this->installed) { ?>
                        <div class="form-row">
                            <div class="field-name">
                                <span>Current agent version: </span>
                            </div>
                            <div class="field-value">
                                <span><?php echo "{$this->agentVersion}"; ?></span>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="field-name">
                                <span>Current agent operating system: </span>
                            </div>
                            <div class="field-value">
                                <span><?php echo "{$this->agentOs}"; ?></span>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="field-name">
                                <span>Current agent architecture: </span>
                            </div>
                            <div class="field-value">
                                <span><?php echo "{$this->agentArch}"; ?></span>
                            </div>
                        </div>
                    <?php } ?> 
                </div>
            </div>
            <?php echo $this->form; ?>
        </div>
    </div>
</div>