<?= $this->response; ?>
<?= $this->renderTabs($this->tabs); ?>

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    <?= pm_Locale::lmsg("setup.view.title"); ?>
                </h3>
            </div>
        </div>
        <div class="content">
            <?= pm_Locale::lmsg("setup.view.description"); ?>
            <br>
            <br>
            
            <form method="post" action="<?= $this->h->url('download-agent', 'setup'); ?>">

                <div class="form-row">
                    <div class="field-name">
                        <span>API Key </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="api_key" value="<?= $this->e->escapeHtml($this->api_key); ?>" 
                            <?php if ($this->extension_installed === "true"): ?> readonly="true" <?php endif; ?>/>
                    </div>
                </div>

                <div class="form-row">
                    <div class="field-name">
                        <span>API Secret </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="api_secret" value="<?= $this->e->escapeHtml($this->api_secret); ?>" 
                            <?php if ($this->extension_installed === "true"): ?> readonly="true" <?php endif; ?>/>
                    </div>
                </div>

                <div class="form-row">
                    <div class="field-name">
                        <span>API Server </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="api_server" value="<?= $this->e->escapeHtml($this->api_server); ?>" 
                            <?php if ($this->extension_installed === "true"): ?> readonly="true" <?php endif; ?>/>
                    </div>
                </div>

                <div class="btns-box">
                    <?php if ($this->extension_installed !== "true"): ?>
                        <div class="box-area">
                            <div class="form-row">
                                <div class="field-name">
                                    <span class="required">*</span>
                                    <span> <?= pm_Locale::lmsg("msg.required"); ?></span>
                                </div>
                                <div class="field-value">
                                    <span class="btn action">
                                    
                                        <button type="submit" name="submit" value="downloadAgent">
                                            <?= pm_Locale::lmsg("setup.view.download_agent"); ?>
                                        </button> 
                                    
                                    </span>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>

            </form>
        </div>
    </div>
</div>

<!-- ========================================= [ JS ] ===================================================================== -->

<script>

    var setLoading = function (toggle) {
        
        // hide button
        toggle.style.display = "None";

        // disable parent
        var parent = toggle.parentNode;
        parent.classList.toggle("disabled");

        // rotating loading spinner
        var spinner = document.createElement("span");
        spinner.classList.toggle("wait");
        spinner.appendChild(document.createTextNode("Please wait"));

        parent.appendChild(spinner);
    } 

    var eventHandler = function (event) {

        // get the clicked element
        var toggle = event.target;

        if (toggle.nodeName.toLowerCase() === "button") {
            
            // for all submit buttons
            if (toggle.type === "submit") {

                // init loading
                setLoading(toggle);
            }
        }
    };

    document.addEventListener("click", eventHandler);

</script>