<?= $this->renderTabs($this->tabs); ?>
<?= $this->response; ?>

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Setup
                </h3>
            </div>
        </div>
        <div class="content">
            <?= pm_Locale::lmsg("setupInfoText"); ?>
            <br>
            <br>
            
            <form method="post" action="<?= $this->h->url('download-agent', 'setup'); ?>">

                <div class="form-row">
                    <div class="field-name">
                        <span>API Key </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="api_key" value="<?= $this->e->escapeHtml($this->api_key); ?>" 
                            <?php if ($this->extension_installed === "true"): ?> readonly="true" <?php endif; ?>/>
                    </div>
                </div>

                <div class="form-row">
                    <div class="field-name">
                        <span>API Secret </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="api_secret" value="<?= $this->e->escapeHtml($this->api_secret); ?>" 
                            <?php if ($this->extension_installed === "true"): ?> readonly="true" <?php endif; ?>/>
                    </div>
                </div>

                <div class="form-row">
                    <div class="field-name">
                        <span>API Server </span>
                        <span class="required">*</span>
                    </div>
                    <div class="field-value">
                        <input type="text" name="api_server" value="<?= $this->e->escapeHtml($this->api_server); ?>" 
                            <?php if ($this->extension_installed === "true"): ?> readonly="true" <?php endif; ?>/>
                    </div>
                </div>

                <div class="btns-box">
                    <?php if ($this->extension_installed !== "true"): ?>
                        <div class="box-area">
                            <div class="form-row">
                                <div class="field-name">
                                    <span class="required">*</span>
                                    <span> Required fields</span>
                                </div>
                                <div class="field-value">
                                    <span class="btn action">
                                        <button type="submit" name="submit" value="downloadAgent">Download Server Agent</button> 
                                    </span>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>

            </form>
        </div>
    </div>
</div>

<!-- ========================================= [ JS ] ===================================================================== -->

<script>
    document.getElementsByName("submit").forEach((node) => { 
        node.addEventListener("click", function(obj) { 
            obj.target.style.display = "None";
            
            var parent = obj.target.parentNode;
            parent.classList.add("disabled");

            var wait = document.createElement("span");
            wait.classList.add("wait");
            wait.appendChild(document.createTextNode("Please wait"));

            parent.appendChild(wait);
        }); 
    });
</script>