<?= $this->renderTabs($this->tabs); ?>
<div id="response">
    <?= $this->response; ?>
</div>

<link href="https://cdn.materialdesignicons.com/1.9.32/css/materialdesignicons.min.css" media="all" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css" rel="stylesheet">

<div class="form-box">
    <div class="box-area">
        <div class="title">
            <div class="title-area">
                <h3>
                    Issues
                </h3>
            </div>
        </div>
        <div class="content">
            
            <div class="msg-box msg-error">
                <div class="msg-content">
                    <span>
                        <div>
                            <b>Beware:</b> This is a warning text indicating that this section should be inspected carefully before clicking a button.
                        </div>
                        <div id="confirmation">

                        </div>
                    </span>
                </div>
            </div>

            <div class="form-row">

                <div class="field-name">
                    Bulk actions
                </div>
            
                <div class="field-value">
                    <div style="display: inline-block; margin-right: 10px;">
                        <a id="bulk-quarantine" style="color: #353535;">
                            <i class="mdi mdi-bug"></i>
                            <span>Move to Quarantine</span>
                        </a>
                    </div>
                    <div style="display: inline-block;">
                        <a id="issue-link">Select / Deselect all issues</a></div>
                    </div>
                </div>

            </div>
            <div class="form-row">

                <div class="field-name">
                    Automatically move domains to quarantine
                </div>

                <div class="field-value">
                    <form method="post" action="<?= $this->h->url('schedule-quarantine', 'issues'); ?>">
                        <input name="action" value="scheduleQuarantine" type="hidden"/>
                        <span style="margin-right: 2px;">
                            <span>None</span>
                            <input type="checkbox" name="quarantine-state[]" value="1" <?php if ($this->quarantine_state == "1"): ?> checked="checked" <?php endif; ?>/>
                            <span style="color: #303030;">|</span>
                        </span>
                        <span style="margin-right: 2px;">
                            <i class="mdi mdi-checkbox-blank-circle" style="color: #fdd835"></i>
                            <span>Yellow</span>
                            <input type="checkbox" name="quarantine-state[]" value="3" <?php if (in_array($this->quarantine_state, array("3", "9"))): ?> checked="checked" <?php endif; ?>/>
                            <span style="color: #303030;">|</span>
                        </span>
                        <span style="margin-right: 2px;">
                            <i class="mdi mdi-checkbox-blank-circle" style="color: #f44336"></i>
                            <span>Red</span>
                            <input type="checkbox" name="quarantine-state[]" value="6" <?php if (in_array($this->quarantine_state, array("6", "9"))): ?> checked="checked" <?php endif; ?>/>
                        </span>
                        <span id="btn-send" class="btn action" style="margin-left: 5px;">
                            <span class="submit-button" sender>Apply</span>
                        </span>
                    </div>
                </form>

            </div>
            
            <div class="btns-box"></div>

            <?php if (count($this->issues) == 0): ?>
                <h4>Congratulations! No issues found.</h4>
            <?php endif; ?>

            <?php foreach ($this->issues as $name => $domain): ?>
                <div class="form-row">

                    <div class="field-name" style="width: 100%">
                        <div style="display: inline-block;">
                            <h4><b><?= $name ?></b></h4>
                        </div>
                        <div style="display: inline-block; margin-left: 5px;">
                            <a id="issue-link-<?= $name; ?>">Select / Deselect all issues</a>
                        </div>
                    </div>

                    <div class="field-value" style="margin-bottom: 15px;"></div>

                    <?php foreach ($domain["results"] as $result): ?>
                        <div class="panel panel-collapsible p-promo panel-collapsed">
                            <div class="panel-wrap">

                                <div class="panel-heading">
                                    <div class="panel-heading-wrap">
                                        <span class="panel-control">

                                            <div style="margin-left: -140px; color: #303030; margin-top: 2px;display: inline-block;">
                                                    <?= date("m/d/o h:i A", $result["lastDate"] / 1000); ?>                                           
                                            </div>
                                            <div style="margin-left: -246px; display: inline-block;">

                                                <form id="falsePositive" method="post" action="<?= $this->h->url('false-positive', 'issues'); ?>">
                                                    <input name="action" value="falsePositive" type="hidden"/>
                                                    <input name="domain" value="<?= $name; ?>" type="hidden"/>
                                                    <input name="resultId" value="<?= $result['id']; ?>" type="hidden"/>
                                                    <input name="file" value="<?= $result['resource'];?>" type="hidden">
                                                    <a onclick="sendForm(this);">
                                                        <i class="mdi mdi-flag"></i>
                                                        <span>False positive</span>
                                                    </a>
                                                </form>

                                            </div>
                                            <div style="margin-left: -256px; margin-top: 2px;display: inline-block;">

                                                <form id="moveToQuarantine" method="post" action="<?= $this->h->url('quarantine', 'issues'); ?>">
                                                    <input name="action" value="moveToQuarantine" type="hidden">
                                                    <input name="domain" value="<?= $name; ?>" type="hidden">
                                                    <input name="file" value="<?= $result['resource'];?>" type="hidden">
                                                    <a onclick="sendForm(this);">
                                                        <i class="mdi mdi-bug"></i>
                                                        <span>Move to Quarantine</span>
                                                    </a>
                                                </form>

                                            </div>

                                        </span>

                                        <div class="panel-heading-name">
                                            
                                            <?php
                                                $left_bubble = $result["severity"] == 1 ? $this->colors[1] : $this->colors[0];
                                                $right_bubble = $result["severity"] > 1 ? $this->colors[2] : $this->colors[0];
                                            ?> 

                                            <span style="margin-right: 5px">
                                                <input type="checkbox" id="issue-<?= $name;?>"/>
                                                <i class="mdi mdi-checkbox-blank-circle" style="color: <?= $left_bubble; ?>"></i>
                                                <i class="mdi mdi-checkbox-blank-circle" style="color: <?= $right_bubble; ?>"></i>
                                            </span>

                                            <span style="font-size: 13px">
                                                <?= $result["resource"]; ?>
                                            </span>
                                        </div>

                                    </div>
                                </div>

                                <div class="panel-content">
                                    <div class="panel-content-wrap">

                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>Occured on</span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= date("m/d/o h:i A", $result["lastDate"] / 1000); ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>Known since</span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= date("m/d/o h:i A", $result["createDate"] / 1000); ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>Path</span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= $result["resource"]; ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>Name</span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= $result["threatname"]; ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>MD5</span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= $result["md5"]; ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>Owner</span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= $result["owner"]; ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>Group</span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= $result["group"]; ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="box-area">
                                            <div class="form-row">
                                                <div class="field-name">
                                                    <span>Permission</span>
                                                </div>
                                                <div class="field-value">
                                                    <span style="vertical-align: middle;">
                                                        <?= $result["permission"]; ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="source-code">
                                            <a>View source code <i class="mdi mdi-arrow-down-drop-circle source-code-icon"></i></a>
                                        
                                            <div class="panel panel-collapsible panel-collapsed source-code-panel" style="margin: 0px; border: 0px">
                                                <div class="panel-wrap">
                                                    <div class="panel-content">
                                                        <div class="panel-content-wrap">
                                                            <pre><code class="html">
                                                                <?= htmlentities(file_get_contents($result["resource"])); ?>
                                                            </code></pre>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    
                    </div>
                </div>
            <?php endforeach; ?> 

        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<script>

    // clean up localstorage key
    localStorage.removeItem("disclaimer");

    function sendForm(element) {
        element.closest("form").submit();
    }

    var setLoading = function (toggle) {
        
        // hide button
        toggle.style.display = "None";

        // disable parent
        var parent = toggle.parentNode;
        parent.classList.toggle("disabled");

        // rotating loading spinner
        var spinner = document.createElement("span");
        spinner.classList.toggle("wait");
        spinner.appendChild(document.createTextNode("Please wait"));

        parent.appendChild(spinner);
    }

    var removeLoading = function (toggle) {
        
        // hide button
        toggle.style.display = "";

        // enable parent
        var parent = toggle.parentNode;
        parent.classList.toggle("disabled");
        
        // remove loading spinner
        toggle.nextElementSibling.remove();
    } 

    var hasParent = function (child, parentSelector) {
        
        // iterate over all parents
        for (; child && child !== document; child = child.parentNode) {

            if (child.matches(parentSelector)) {
                return true;
            }
        }

        return false;
    }

    var eventHandler = function (event) {

        // get the clicked element
        var toggle = event.target;

        // get the nodename
        var nodeName = toggle.nodeName.toLowerCase();

        // expanding issue panel
        if (hasParent(toggle, ".panel-heading")) { 

            // open panel only if necessary
            if (nodeName == "input" || nodeName == "a") {
                return;
            }

            // exclude the action links for moving to quarantine
            // and false positive 
            if (hasParent(toggle, "#moveToQuarantine") || hasParent(toggle, "#falsePositive")) {
                return;
            }

            toggle.closest(".panel").classList.toggle("panel-collapsed");
            toggle.closest(".panel").classList.toggle("panel-expanded");
        }

        // bulk quarantine action
        if (hasParent(toggle, "#bulk-quarantine")) {

            // filter issue which are checked
            var issues = Array.from(document.querySelectorAll("input[id^='issue-']")).filter(function (issue) { 
                return issue.checked; 
            });

            var payload = [];

            // append information of each issue to the payload
            issues.forEach(function (issue) {
                
                // navigate top
                var heading = issue.closest(".panel-heading");

                // get quarantine form
                var form = heading.querySelectorAll("form")[1];

                payload.push({
                    domain: form.elements.domain.value,
                    file: form.elements.file.value
                });
            });

            // send ajax request
            var form = new FormData();
            form.append("action", "bulk-quarantine");
            form.append("issues", JSON.stringify(payload));
            
            var xhr = new XMLHttpRequest();
            xhr.onload = function(){ 

                var response = JSON.parse(xhr.responseText);
                    
                // something went wrong
                if (response.hasOwnProperty("error")) {
                    document.getElementById("response").innerHTML = response.error;
                    return;
                }

                document.getElementById("response").innerHTML = response.html;
                window.location.reload(true);
            }

            xhr.open ("POST", "<?= $this->h->url('bulk-quarantine', 'issues'); ?>", false);
            xhr.send (form);
        }

        if (nodeName === "span") {
            
            // for the apply button
            if (toggle.hasAttribute("sender")) {

                // skip disabled
                if (toggle.parentNode.classList.contains("disabled")) {
                    return;
                }

                // init loading
                setLoading(toggle);

                // check whether the disclaimer has been accepted
                var disclaimer = localStorage.getItem("disclaimer");
                if (disclaimer === null) {

                    // remove confirmation element
                    var confirmation = document.getElementById("confirmation");
                    while (confirmation.firstChild) {
                        confirmation.removeChild(confirmation.firstChild);
                    }

                    // create confirmation element
                    // parent node
                    var disclaimerParent = document.createElement("span");

                    // confirmation message
                    var message = document.createTextNode(" Click the checkbox if you have read the disclaimer.");

                    // confirmation checkbox
                    var checkbox = document.createElement("input");
                    checkbox.type = "checkbox";

                    checkbox.addEventListener("change", function() {

                        // when previously unset
                        if (localStorage.getItem("disclaimer") === null) {
                            localStorage.setItem("disclaimer", "true");
                        } else {
                            localStorage.removeItem("disclaimer");
                        }
                        
                        // enable button
                        toggle.parentNode.classList.toggle("disabled");
                    });

                    // append to DOM
                    disclaimerParent.appendChild(checkbox);
                    disclaimerParent.appendChild(message);
                    confirmation.appendChild(disclaimerParent);

                    // remove animation but disable the button
                    removeLoading(toggle);
                    toggle.parentNode.classList.toggle("disabled");

                } else {

                    // submit form
                    toggle.closest("form").submit();
                }
            }
        }
        
        if (nodeName === "a") {

            // expanding source code in issue panel
            if (hasParent(toggle, ".source-code")) {

                // querying from parent element
                var panel = toggle.parentElement.querySelector(".source-code-panel");
                var icon = toggle.parentElement.querySelector(".source-code-icon");

                panel.classList.toggle("panel-collapsed");
                panel.classList.toggle("panel-expanded");

                icon.classList.toggle("mdi-arrow-down-drop-circle");
                icon.classList.toggle("mdi-arrow-up-drop-circle");
            }

            // selecting and (un)checking issues by domain
            if (toggle.id.startsWith("issue-link-")) {

                // split between e.g issue-link-test.com
                var parts = toggle.id.split("-");

                var domain = parts[parts.length - 1];

                // select the checked state of the first issue
                var checked = document.querySelector("[id='issue-" + domain + "']").checked;

                // apply to all
                document.querySelectorAll("[id='issue-" + domain + "']").forEach(function(issue) { 
                    issue.checked = !checked; 
                });
            }

            // selecting and (un)checking all issues 
            if (toggle.id === "issue-link") {

                // select the checked state of the first issue
                var checked = document.querySelector("input[id^='issue-']").checked;

                // apply to all 
                document.querySelectorAll("input[id^='issue-']").forEach(function (issue) { 
                    issue.checked = !checked; 
                });
            }
        }
    };

    document.addEventListener("click", eventHandler);

</script>